CC := vc

NDK_INC ?= ~/Developer/Amiga/sdk/NDK_3.9/Include/include_h

TARGET := dist/HappyAmigaClock

SOURCES := $(sort $(shell find src -type f -name '*.c'))
HEADERS := $(sort $(shell find include -type f -name '*.h'))
FONT_BITMAP := src/font_bitmap.inc
OBJECTS := $(patsubst src/%.c,build/vbcc/%.o,$(SOURCES))

CPPFLAGS := -Iinclude -I$(NDK_INC)
CFLAGS := +kick13 -cpu=68000 -O2
LDLIBS := $(VBCC)/targets/m68k-amigaos/lib/amiga.lib -lamiga

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(OBJECTS)
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -o $@ $(OBJECTS) $(LDLIBS)

build/vbcc/%.o: src/%.c $(HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

build/vbcc/font.o: $(FONT_BITMAP)

clean:
	rm -rf build/vbcc
	rm -f $(TARGET)
