#!/usr/bin/env python3
"""Generate native-size monochrome numeral masks for BltTemplate."""

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FONT = Path("/Library/Fonts/Roboto_Light.ttf")
DEFAULT_OUTPUT = ROOT / "src" / "font_bitmap.inc"
CHARS = "0123456789:/"
SCALE = 4

# The time styles are used by hh:mm and hh:mm:ss; the date has its own style.
SIZES = (
    ("compact", 52, 88, "time"),
    ("large", 44, 72, "time"),
    ("small", 16, 18, "date"),
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate embedded Amiga clock font bitmaps."
    )
    parser.add_argument(
        "--time-font",
        type=Path,
        default=DEFAULT_FONT,
        help="TTF/OTF/TTC used for hh:mm and hh:mm:ss",
    )
    parser.add_argument(
        "--date-font",
        type=Path,
        default=DEFAULT_FONT,
        help="TTF/OTF/TTC used for the date",
    )
    parser.add_argument(
        "--time-face",
        type=int,
        default=0,
        help="face/style index inside the time font collection (default: 0)",
    )
    parser.add_argument(
        "--date-face",
        type=int,
        default=0,
        help="face/style index inside the date font collection (default: 0)",
    )
    parser.add_argument(
        "--time-threshold",
        type=int,
        default=112,
        help="time antialias-to-monochrome threshold, 0..255 (default: 112)",
    )
    parser.add_argument(
        "--date-threshold",
        type=int,
        default=112,
        help="date antialias-to-monochrome threshold, 0..255 (default: 112)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"generated include file (default: {DEFAULT_OUTPUT})",
    )
    return parser.parse_args()


def validate_style(label, font_path, face, threshold):
    if not font_path.is_file():
        raise SystemExit(f"{label} font not found: {font_path}")
    if face < 0:
        raise SystemExit(f"{label} face index must be zero or greater")
    if not 0 <= threshold <= 255:
        raise SystemExit(f"{label} threshold must be between 0 and 255")


def rasterize(width, height, font_path, face, threshold):
    """Fit by height with one uniform scale; never stretch the glyph."""
    trial = ImageFont.truetype(str(font_path), 100 * SCALE, index=face)
    probe = ImageDraw.Draw(Image.new("L", (1, 1)))
    boxes = [probe.textbbox((0, 0), c, font=trial) for c in "0123456789"]
    trial_height = max(b[3] for b in boxes) - min(b[1] for b in boxes)
    size = round(100 * SCALE * ((height - 4) * SCALE) / trial_height)
    font = ImageFont.truetype(str(font_path), size, index=face)
    boxes = [probe.textbbox((0, 0), c, font=font) for c in "0123456789"]
    top = min(b[1] for b in boxes)
    bottom = max(b[3] for b in boxes)
    result = []

    for char in CHARS:
        hi = Image.new("L", (width * SCALE, height * SCALE))
        draw = ImageDraw.Draw(hi)
        advance = draw.textlength(char, font=font)
        x = (hi.width - advance) / 2
        y = ((hi.height - (bottom - top)) / 2) - top
        draw.text((x, y), char, fill=255, font=font)
        glyph = hi.resize((width, height), Image.Resampling.LANCZOS)
        glyph = glyph.point(lambda p: 255 if p >= threshold else 0)
        stride = (width + 31) // 32
        encoded = []
        for py in range(height):
            words = [0] * stride
            for px in range(width):
                if glyph.getpixel((px, py)):
                    words[px // 32] |= 1 << (31 - (px % 32))
            encoded.append(words)
        result.append(encoded)
    return result


def describe_style(label, style):
    name = style["font"].name.replace("*/", "")
    return (
        f"   {label}: {name}, face {style['face']}, "
        f"threshold {style['threshold']}."
    )


def generate(args):
    styles = {
        "time": {
            "font": args.time_font,
            "face": args.time_face,
            "threshold": args.time_threshold,
        },
        "date": {
            "font": args.date_font,
            "face": args.date_face,
            "threshold": args.date_threshold,
        },
    }

    for label, style in styles.items():
        validate_style(
            label, style["font"], style["face"], style["threshold"]
        )

    lines = [
        "/* Generated by tools/generate_font_bitmap.py.",
        describe_style("Time", styles["time"]),
        describe_style("Date", styles["date"]),
        "*/",
    ]

    for name, width, height, style_name in SIZES:
        style = styles[style_name]
        rows = rasterize(
            width,
            height,
            style["font"],
            style["face"],
            style["threshold"],
        )
        stride = (width + 31) // 32
        lines.extend(
            [
                f"static const ULONG glyph_{name}[12][{height}][{stride}] =",
                "{",
            ]
        )
        for char, encoded in zip(CHARS, rows):
            lines.append(f"    /* {char} */")
            lines.append("    {")
            for words in encoded:
                values = ", ".join(f"0x{word:08x}UL" for word in words)
                lines.append(f"        {{ {values} }},")
            lines.append("    },")
        lines.extend(["};", ""])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    generate(parse_args())
