#!/usr/bin/env python3
"""Generate native-size monochrome Roboto numeral masks for BltTemplate."""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

FONT = Path("/Library/Fonts/Roboto_Light.ttf")
OUT = Path(__file__).resolve().parents[1] / "src" / "font_bitmap.inc"
CHARS = "0123456789:/"
SCALE = 4


def rasterize(width, height):
    """Fit by height with one uniform scale; never stretch the glyph."""
    trial = ImageFont.truetype(str(FONT), 100 * SCALE)
    probe = ImageDraw.Draw(Image.new("L", (1, 1)))
    boxes = [probe.textbbox((0, 0), c, font=trial) for c in "0123456789"]
    trial_height = max(b[3] for b in boxes) - min(b[1] for b in boxes)
    size = round(100 * SCALE * ((height - 4) * SCALE) / trial_height)
    font = ImageFont.truetype(str(FONT), size)
    boxes = [probe.textbbox((0, 0), c, font=font) for c in "0123456789"]
    top = min(b[1] for b in boxes)
    bottom = max(b[3] for b in boxes)
    result = []

    for char in CHARS:
        hi = Image.new("L", (width * SCALE, height * SCALE))
        draw = ImageDraw.Draw(hi)
        advance = draw.textlength(char, font=font)
        x = (hi.width - advance) / 2
        y = ((hi.height - (bottom - top)) / 2) - top
        draw.text((x, y), char, fill=255, font=font)
        glyph = hi.resize((width, height), Image.Resampling.LANCZOS)
        glyph = glyph.point(lambda p: 255 if p >= 112 else 0)
        stride = (width + 31) // 32
        encoded = []
        for py in range(height):
            words = [0] * stride
            for px in range(width):
                if glyph.getpixel((px, py)):
                    words[px // 32] |= 1 << (31 - (px % 32))
            encoded.append(words)
        result.append(encoded)
    return result


sizes = (
    ("compact", 52, 88),  # hh:mm
    ("large", 36, 64),    # hh:mm:ss
    ("small", 16, 24),    # date
)

lines = [
    "/* Generated by tools/generate_font_bitmap.py from Roboto Light.",
    "   Roboto is Copyright 2011 Google Inc., licensed under Apache-2.0. */",
]
for name, width, height in sizes:
    rows = rasterize(width, height)
    stride = (width + 31) // 32
    lines.extend(
        [
            f"static const ULONG glyph_{name}[12][{height}][{stride}] =",
            "{",
        ]
    )
    for char, encoded in zip(CHARS, rows):
        lines.append(f"    /* {char} */")
        lines.append("    {")
        for words in encoded:
            values = ", ".join(f"0x{word:08x}UL" for word in words)
            lines.append(f"        {{ {values} }},")
        lines.append("    },")
    lines.extend(["};", ""])
OUT.write_text("\n".join(lines) + "\n")
